{% set name = "python-augeas" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python-augeas-{{ version }}.tar.gz
  sha256: d2334710e12bdec8b6633a7c2b72df4ca24ab79094a3c9e699494fdb62054a10
  patches:
    # https://github.com/hercules-team/python-augeas/pull/53
    - 0001-Ensure-exclude-is-a-tuple.patch

build:
  number: 0
  # https://github.com/hercules-team/augeas/issues/612
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - cffi >=1.0.0
    - pip
    - python
    - setuptools
    - libaugeas
  run:
    - cffi >=1.0.0
    - python

test:
  imports:
    - augeas
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://augeas.net/
  summary: Python bindings for Augeas
  license: LGPL-2.1-only
  license_file: COPYING

extra:
  recipe-maintainers:
    - nehaljwani
